### ISSUE TITLE
Build failing with new TypeScript Build Structure

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#143]
Building with `npm run build` is currently failing after the merge of #128 due to not exposed types by the `devp2p` package. I would assume that this was not triggered by node or browser tests since these are not running the whole build process but use `ts-node` respectively `karma-typescript` and the code paths on compilation are not reaching the missing type definitions.

Anyhow 😄 : this needs an update on the devp2p library. Will extract this to a separate issue here since I would like to concentrate on transitioning some js code parts to TypeScript today, it also make sense to wait for https://github.com/ethereumjs/ethereumjs-vm/issues/890 to be in place (should hopefully be relatively easy to the activate for a non-monorepo package as well for the time being?), since integration will be significantly easier then.

**Comment by holgerd77** [comment]
Ah, and for the record, following console output:

```shell
$ npm run build

> ethereumjs-client@0.0.6 build /ethereumjs-client
> tsc -p ./tsconfig.prod.json && npm run build:browser

node_modules/ethereumjs-devp2p/dist/dpt/kbucket.d.ts:3:22 - error TS7016: Could not find a declaration file for module 'k-bucket'. '/ethereumjs-client/node_modules/k-bucket/index.js' implicitly has an 'any' type.
  Try `npm install @types/k-bucket` if it exists or add a new declaration (.d.ts) file containing `declare module 'k-bucket';`

3 import _KBucket from 'k-bucket';
                       ~~~~~~~~~~

node_modules/ethereumjs-devp2p/dist/dpt/server.d.ts:3:22 - error TS7016: Could not find a declaration file for module 'lru-cache'. '/ethereumjs-client/node_modules/lru-cache/index.js' implicitly has an 'any' type.
  Try `npm install @types/lru-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'lru-cache';`

3 import LRUCache from 'lru-cache';
                       ~~~~~~~~~~~

node_modules/ethereumjs-devp2p/dist/rlpx/peer.d.ts:3:24 - error TS7016: Could not find a declaration file for module 'bl'. '/ethereumjs-client/node_modules/bl/bl.js' implicitly has an 'any' type.
  Try `npm install @types/bl` if it exists or add a new declaration (.d.ts) file containing `declare module 'bl';`

3 import BufferList from 'bl';
                         ~~~~

node_modules/ethereumjs-devp2p/dist/rlpx/rlpx.d.ts:4:22 - error TS7016: Could not find a declaration file for module 'lru-cache'. '/ethereumjs-client/node_modules/lru-cache/index.js' implicitly has an 'any' type.
  Try `npm install @types/lru-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'lru-cache';`

4 import LRUCache from 'lru-cache';
                       ~~~~~~~~~~~


Found 4 errors.
```

**Comment by holgerd77** [comment]
Fixed by https://github.com/ethereumjs/ethereumjs-devp2p/issues/87, will close.
